title: Audrius meme blog
author: @Audrius59
email: audrius.s59@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In my blog we gonna look at the most awesome memes according to me!
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
